//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionData
    {
        public string SessionID { get; set; }
        public Nullable<System.Guid> CompiledDefinition { get; set; }
        public Nullable<System.Guid> SnapshotDataID { get; set; }
        public Nullable<bool> IsPermanentSnapshot { get; set; }
        public string ReportPath { get; set; }
        public int Timeout { get; set; }
        public Nullable<int> AutoRefreshSeconds { get; set; }
        public System.DateTime Expiration { get; set; }
        public byte[] ShowHideInfo { get; set; }
        public byte[] DataSourceInfo { get; set; }
        public System.Guid OwnerID { get; set; }
        public string EffectiveParams { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<bool> HasInteractivity { get; set; }
        public Nullable<System.DateTime> SnapshotExpirationDate { get; set; }
        public Nullable<System.DateTime> HistoryDate { get; set; }
        public Nullable<double> PageHeight { get; set; }
        public Nullable<double> PageWidth { get; set; }
        public Nullable<double> TopMargin { get; set; }
        public Nullable<double> BottomMargin { get; set; }
        public Nullable<double> LeftMargin { get; set; }
        public Nullable<double> RightMargin { get; set; }
        public Nullable<bool> AwaitingFirstExecution { get; set; }
        public string EditSessionID { get; set; }
        public byte[] DataSetInfo { get; set; }
        public string SitePath { get; set; }
        public int SiteZone { get; set; }
        public string ReportDefinitionPath { get; set; }
    }
}
